#!/bin/bash

sudo apt-get --force-yes --yes install libnss-mdns lxc

sudo lxc-create -n sessility -t ubuntu -- -r precise -a i386 -b $USER

sudo lxc-start -dn sessility

IP=`awk '{ print $4,$3 }' /var/lib/misc/dnsmasq.leases | column -t|grep sessility|grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
CURPATH=`pwd`
POSTCREATE=$CURPATH/setup-lxc

echo "Waiting for sessility to start..."
sleep 5

echo "Establishing connection to sessility using ip: (${IP})"
ssh -oStrictHostKeyChecking=no $IP 'bash -s' < $POSTCREATE
